---
apiVersion: batch/v1
kind: Job
metadata:
  name: deploy_service_a
spec:
  template:
    spec:
      volumes:
      - name: deploy-git
        secret:
          secretName: deploy-git
          defaultMode: 0400
      containers:
      - name: apply
        image: elmariofredo/relax:v0.2
        volumeMounts:
        - name: deploy-git
          mountPath: /root/.ssh
          readOnly: true
        args:
        - git@git.whatever.net:deploy/environments/alfa/service_a.git
        - service_a
      restartPolicy: OnFailure
      serviceAccount: deploy
  backoffLimit: 10
